language: ruby
rvm:
- 2.3.3 #reasonably recent
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH #for slimer
addons:
  firefox: "50.0" # for slimer
cache: bundler # Cache rubygems to speed up the build
before_script:
  - . $HOME/.nvm/nvm.sh # Allows us to install a more recent node
  - nvm install stable # Install it
  - nvm use stable # Use it
  - npm install # Install project dependencies
  - npm install -g casperjs slimerjs@0.10.3 a11y # Install dependencies which prefer to be global
  - sh -e /etc/init.d/xvfb start # start xvfb for slimer
script: npm run test
